/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IBancoronverter,
  IBancoronverterInterface,
} from "../IBancoronverter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_reserveToken",
        type: "address",
      },
    ],
    name: "reserveBalance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "token",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IBancoronverter__factory {
  static readonly abi = _abi;
  static createInterface(): IBancoronverterInterface {
    return new utils.Interface(_abi) as IBancoronverterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBancoronverter {
    return new Contract(address, _abi, signerOrProvider) as IBancoronverter;
  }
}
