/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ICurveRegistry,
  ICurveRegistryInterface,
} from "../ICurveRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
    ],
    name: "get_pool_info",
    outputs: [
      {
        internalType: "uint256[8]",
        name: "balances",
        type: "uint256[8]",
      },
      {
        internalType: "uint256[8]",
        name: "underlying_balances",
        type: "uint256[8]",
      },
      {
        internalType: "uint256[8]",
        name: "decimals",
        type: "uint256[8]",
      },
      {
        internalType: "uint256[8]",
        name: "underlying_decimals",
        type: "uint256[8]",
      },
      {
        internalType: "address",
        name: "lp_token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "A",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "fee",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ICurveRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): ICurveRegistryInterface {
    return new utils.Interface(_abi) as ICurveRegistryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICurveRegistry {
    return new Contract(address, _abi, signerOrProvider) as ICurveRegistry;
  }
}
