/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ICurveCalculator,
  ICurveCalculatorInterface,
} from "../ICurveCalculator";

const _abi = [
  {
    inputs: [
      {
        internalType: "int128",
        name: "nCoins",
        type: "int128",
      },
      {
        internalType: "uint256[8]",
        name: "balances",
        type: "uint256[8]",
      },
      {
        internalType: "uint256",
        name: "amp",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "fee",
        type: "uint256",
      },
      {
        internalType: "uint256[8]",
        name: "rates",
        type: "uint256[8]",
      },
      {
        internalType: "uint256[8]",
        name: "precisions",
        type: "uint256[8]",
      },
      {
        internalType: "bool",
        name: "underlying",
        type: "bool",
      },
      {
        internalType: "int128",
        name: "i",
        type: "int128",
      },
      {
        internalType: "int128",
        name: "j",
        type: "int128",
      },
      {
        internalType: "uint256[100]",
        name: "dx",
        type: "uint256[100]",
      },
    ],
    name: "get_dy",
    outputs: [
      {
        internalType: "uint256[100]",
        name: "dy",
        type: "uint256[100]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ICurveCalculator__factory {
  static readonly abi = _abi;
  static createInterface(): ICurveCalculatorInterface {
    return new utils.Interface(_abi) as ICurveCalculatorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICurveCalculator {
    return new Contract(address, _abi, signerOrProvider) as ICurveCalculator;
  }
}
