/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IMulticall, IMulticallInterface } from "../IMulticall";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "pooladdr",
        type: "address",
      },
      {
        components: [
          {
            internalType: "address",
            name: "from",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "fromBalancePreEthBefore",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "fromBalancePreEthAfter",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "poolLiqudityPre",
            type: "uint256",
          },
          {
            internalType: "int24",
            name: "tick",
            type: "int24",
          },
          {
            internalType: "uint256",
            name: "deadlineBlockNumer",
            type: "uint256",
          },
        ],
        internalType: "struct PreCheckParams",
        name: "checkparams",
        type: "tuple",
      },
      {
        internalType: "bytes",
        name: "datas",
        type: "bytes",
      },
    ],
    name: "call",
    outputs: [
      {
        internalType: "bytes",
        name: "results",
        type: "bytes",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "pooladdr",
        type: "address",
      },
      {
        components: [
          {
            internalType: "address",
            name: "from",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "fromBalancePreEthBefore",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "fromBalancePreEthAfter",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "poolLiqudityPre",
            type: "uint256",
          },
          {
            internalType: "int24",
            name: "tick",
            type: "int24",
          },
          {
            internalType: "uint256",
            name: "deadlineBlockNumer",
            type: "uint256",
          },
        ],
        internalType: "struct PreCheckParams",
        name: "checkparams",
        type: "tuple",
      },
      {
        internalType: "bytes[]",
        name: "datas",
        type: "bytes[]",
      },
      {
        internalType: "address[]",
        name: "addrs",
        type: "address[]",
      },
      {
        internalType: "int8[]",
        name: "calltypes",
        type: "int8[]",
      },
    ],
    name: "multicall",
    outputs: [
      {
        internalType: "bytes[]",
        name: "results",
        type: "bytes[]",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
];

export class IMulticall__factory {
  static readonly abi = _abi;
  static createInterface(): IMulticallInterface {
    return new utils.Interface(_abi) as IMulticallInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMulticall {
    return new Contract(address, _abi, signerOrProvider) as IMulticall;
  }
}
