/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ITrendingCall, ITrendingCallInterface } from "../ITrendingCall";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "spender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "placeOrderApprove",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "placeOrderFixTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ITrendingCall__factory {
  static readonly abi = _abi;
  static createInterface(): ITrendingCallInterface {
    return new utils.Interface(_abi) as ITrendingCallInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITrendingCall {
    return new Contract(address, _abi, signerOrProvider) as ITrendingCall;
  }
}
